name = "kaluwala-telegram"
main = "src/index.js"
compatibility_date = "2025-10-31"
type = "javascript"

[observability]
	[observability.logs]
	enabled = false
	# head_sampling_rate is a float between 0 and 1 (1 = sample all heads). Keep as number.
	head_sampling_rate = 1
	invocation_logs = true

[[d1_databases]]
	binding = "DB"  # This is what will appear as env.DB
	database_name = "kaluwala_db"
	database_id = "a264c880-5aa2-41f2-bb48-25f560b0db4a"
